services:
    beeflow.sql_query_manager:
        class: Beeflow\SQLQueryManager\Lib\SQLQueryManager
        arguments: ["@service_container"]

    beeflow.sql_manager.vartypes.Boolean:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFBoolean

    beeflow.sql_manager.vartypes.Byte:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFByte

    beeflow.sql_manager.vartypes.Date:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFDate

    beeflow.sql_manager.vartypes.Double:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFDouble

    beeflow.sql_manager.vartypes.Email:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFEmail

    beeflow.sql_manager.vartypes.Float:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFFloat

    beeflow.sql_manager.vartypes.Integer:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFInteger

    beeflow.sql_manager.vartypes.Nip:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFNip

    beeflow.sql_manager.vartypes.PsqlSecureString:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFPsqlSecureString

    beeflow.sql_manager.vartypes.SecureString:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFSecureString

    beeflow.sql_manager.vartypes.String:
        class: Beeflow\SQLQueryManager\Lib\Vartypes\BFString
